### ISSUE TITLE
As a player, I want to read the rules of the game, in order for me to understand it.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-client#98]
### Acceptance Criteria:

- [x] The rules are accessible from the dashboard.
- [x] The rules explain the game.

### Development Tasks:

- [x] sopra-fs23-group-33/sopra-client#80
- [x] sopra-fs23-group-33/sopra-client#21
- [x] sopra-fs23-group-33/sopra-client#81

**Comment by stsaxe** [comment]
This is not a server task

**Comment by COrtsJosep** [comment]
All devtasks are successfully closed, so I'm marking this US as completed.
